#############################################################
###                        THUNAR                         ###
#############################################################

##############################
### PROPERTIES
##############################
windowrule = float 1, size 1280 720, match:class xdg-desktop-portal-gtk
windowrule = float 1, size 1280 720, match:class [Tt]hunar

##############################
### KEYBIND
##############################
bind = $mod, E, exec, thunar
