#############################################################
###                        WAYBAR                         ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = waybar
exec-once = swaync &

##############################
### KEYBINDS
##############################
bind = $mod SHIFT, W, exec, waybar
bind = $mod, N, exec, swaync-client -t -sw
