# BEGIN_KITTY_FONTS
font_family      family="ComicShannsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_KEYBINDS
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
# END_KITTY_KEYVINDS

scrollback_lines 3000

# BEGIN_KITTY_THEME
include theme.conf
# END_KITTY_THEME
