#############################
# GENERAL FEEL
#############################

# Cursor
shell_integration no-cursor
cursor_shape beam

# Window
window_padding_width 10
window_padding_height 10
font_size 12.5

#############################
# COLORS
#############################

background           #070314
foreground           #ffeaef
cursor               #fbb767
cursor_text_color    #070314

selection_background #7d0573
selection_foreground #ffeaef

color0  #070314
color8  #34313F

color1  #7d0573
color9  #95328C

color2  #c89de4
color10 #D2AFE9

color3  #fbb767
color11 #FCC483

color4  #51356f
color12 #715A89

color5  #ff01bb
color13 #FF2FC7

color6  #9377a0
color14 #A790B1

color7  #ffeaef
color15 #FFEEF2
