#############################
# GENERAL FEEL
#############################

# Cursor
shell_integration no-cursor
cursor_shape beam

# Window
window_padding_width 10
window_padding_height 10
font_size 12.5

