#############################################################
###                     HYPRLAND APPS                     ###
#############################################################

exec-once = xwaylandvideobridge &
exec-once = systemctl --user start hyprpolkitagent

bind = $mod, P, exec, hyprpicker --autocopy

#############################################################
###                         MISC                          ###
#############################################################

##############################
### PROPERTIES
##############################

# nwg-look
windowrule = float 1, match:class nwg-look

##############################
### AUTOSTART
##############################
exec = nwg-look -a
