#############################################################
###                     HYPRLAND APPS                     ###
#############################################################

exec-once = xwaylandvideobridge &
exec-once = systemctl --user start hyprpolkitagent

source = idle.conf
source = status_bar.conf
source = wallpaper_manager.conf
source = clipboard_manager.conf
source = screenshot.conf

source = app_launcher.conf
source = file_explorer.conf
source = image_viewer.conf
source = terminal_emulator.conf
source = theme_switcher.conf

#############################################################
###                         MISC                          ###
#############################################################

##############################
### PROPERTIES
##############################

# nwg-look
windowrule = float 1, match:class nwg-look

##############################
### AUTOSTART
##############################
exec = nwg-look -a
