#############################################################
###                       HYPRIDLE                        ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = systemctl --user start hypridle
