#############################################################
###                       SWAYIDLE                        ###
#############################################################

source = screenlock.conf

##############################
### AUTOSTART
##############################
exec-once = swayidle -w timeout 300  "$screenlock_cmd" \
                        timeout 360  'hyprctl dispatch dpms off' \
                        timeout 420  'systemctl suspend' \
                            resume   'hyprctl dispatch dpms on' \
                        before-sleep "$screenlock_cmd"
