#############################################################
###                         KITTY                         ###
#############################################################

##############################
### VARIABLES
##############################
$terminal = kitty

##############################
### PROPERTIES
##############################
# windowrule = no_blur 1, match:class .*kitty.*
# windowrule = match:class kitty, float 1

##############################
### KEYBINDS
##############################
bind = $mod, RETURN,   exec, kitty
bind = $mod, KP_Enter, exec, kitty
