#############################################################
###                    THEME SWITCHER                     ###
#############################################################

##############################
### KEYBINDS
##############################
bind = $mod, T, exec, pgrep wofi || \
                      ~/.config/theme_switcher/scripts/theme-switcher.sh
