#############################################################
###                        UTILITY                        ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = ntfy subscribe --config ~/.config/ntfy/client.yml --from-config

##############################
### KEYBINDS
##############################
bind = $mod,       R, exec, pgrep wofi && pkill wofi || ~/.config/scripts/remyndr/quick_alarm.sh
bind = $mod SHIFT, R, exec, pgrep wofi && pkill wofi || ~/.config/scripts/remyndr/ls.sh
