#############################################################
###                         COPYQ                         ###
#############################################################

##############################
### Properties
##############################
windowrule = float 1, match:class com.github.hluk.copyq
windowrule = stay_focused 1, match:class com.github.hluk.copyq
windowrule = move cursor_x cursor_y, match:class com.github.hluk.copyq

##############################
### AUTOSTART
##############################
exec-once = copyq --start-server

##############################
### KEYBINDS
##############################
bind = $mod, V, exec, copyq toggle
