[config.wallpaper]
command = "hyprctl hyprpaper wallpaper 'DP-1,{{ image }}'"
set = true

[templates.hyprland]
input_path = "./hyprland-colors.conf"
output_path = "~/.config/.colors/hyprland-colors.conf"
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = "./colors.css"
output_path = "~/.config/.colors/waybar-colors.css"

[templates.wofi]
input_path = "./colors.css"
output_path = "~/.config/.colors/wofi-colors.css"
