$image = {{image}}
<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>

<* for name, value in colors *>
${{name}}_half_opac = rgba({{value.default.hex_stripped}}55)
<* endfor *>