#############################################################
###                          FEH                          ###
#############################################################

##############################
### PROPERTIES
##############################
windowrule = float 1, match:class feh
windowrule = opacity 1 override, match:class feh
