#############################################################
###                         WOFI                         ###
#############################################################

##############################
### PROPERTIES
##############################
# layerrule = blur, wofi

##############################
### KEYBINDS
##############################
bind = $mod, KP_Add, exec, pgrep wofi || wofi
bind = $mod, insert, exec, pgrep wofi || wofi
