#############################################################
###                         APPS                          ###
#############################################################

source = discord.conf
source = easy_effects.conf
source = steam.conf
source = zen.conf

#############################################################
###                       MISC APPS                       ###
#############################################################

##############################
### MINECRAFT
##############################
windowrule = opacity 1 override, match:title .*Minecraft.*

##############################
### GODOT
##############################
windowrule = tile 1, match:class Godot
bind = $mod, G, exec, ~/Documents/gamedev/Godot_v4.5.1-stable_linux.x86_64 --display-driver wayland --single-window

#############################################################
###                       TEMP APPS                       ###
#############################################################

##############################
### DEBUG TOOL
##############################
# windowrule = float 1, match:class Debug Tool

##############################
### QT DESIGNER
##############################
# windowrule = noinitialfocus 1, match:class Designer
# bind = $mod, D, exec, docker exec -it -e DISPLAY=:1 data_collection_dev_rokko designer
