#############################################################
###                        DISCORD                        ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = discord &

##############################
### PROPERTIES
##############################
windowrule = workspace special:discord silent, match:class discord
windowrule = opacity 0.8 override, match:class discord
windowrule = opacity 1 override, match:title .*(art|videos).*- Discord

##############################
### KEYBINDS
##############################
bind = $mod,       Z, togglespecialworkspace, discord
bind = $mod SHIFT, Z, movetoworkspacesilent,  special:discord
bindl = ALT, grave, pass, class:^(discord)$
