#############################################################
###                     EASY EFFECTS                      ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = easyeffects &

##############################
### PROPERTIES
##############################
windowrule = workspace special:easy_effects silent, match:class com.github.wwmm.easyeffects

##############################
### KEYBINDS
##############################
bind = $mod,       C, togglespecialworkspace, easy_effects
bind = $mod SHIFT, C, movetoworkspacesilent,  special:easy_effects
