#############################################################
###                         STEAM                         ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = steam &

##############################
### PROPERTIES
##############################
windowrule = float 1, match:class steam
windowrule = workspace special:steam silent, match:class steam

##############################
### KEYBINDS
##############################
bind = $mod,       X, togglespecialworkspace, steam
bind = $mod SHIFT, X, movetoworkspacesilent,  special:steam
