#############################################################
###                          ZEN                          ###
#############################################################

##############################
### PROPERTIES
##############################
# general properties
# windowrule = opacity 1 override, match:class zen
# windowrule = opacity 1 override, match:class google-chrome

# youtube properties
windowrule = opacity 1 override, match:title .*- YouTube.*

# twitch properties
windowrule = opacity 1 override, match:title .*- Twitch.*

# 9anime properties
windowrule = opacity 1 override, match:title Watch .* on 9anime .*
windowrule = opacity 1 override, match:title .* Episode .* 9anime .*
