#############################################################
###                       HYPRLOCK                        ###
#############################################################

##############################
### VARIABLES
##############################
$screenlock_name=hyprlock
$screenlock_cmd=hyprlock

##############################
### KEYBINDS
##############################
bind = $mod, L, exec, $screenlock_cmd
