#############
### VARIABLES
#############

source = ~/.config/.colors/hyprland-colors.conf

$font = ComicShannsMono Nerd Font
$emoji_font = Font Awesome
$emoji_font_size = 55
$emoji_spacing = 100

#############
### GENERAL
#############

general {
    hide_cursor = false
    ignore_empty_input = true
    grace = 30
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

#############
### BACKGROUND IMAGE
#############

background {
    monitor =
    path = $image
    blur_passes = 0
    # reload_time= 5
    # reload_cmd= find ~/.config/wallpapers -type f | head -n 1
}

#############
### BACKGROUND BOX
#############

shape {
    monitor = 
    size = 600,550
    rounding = 10
    position = 0, 40
    halign = center
    valign = center
    # color = rgba(0, 0, 0, 0.5)
    color = $surface_half_opac
}

shape {
    monitor = 
    size = 90,90
    rounding = -1
    position = 0, -150
    halign = center
    valign = center
    # color = rgba(0, 0, 0, 0.5)
    color = $surface
}

shape {
    monitor = 
    size = 90,90
    rounding = -1
    position = -100, -150
    halign = center
    valign = center
    # color = rgba(0, 0, 0, 0.5)
    color = $surface
}

shape {
    monitor = 
    size = 90,90
    rounding = -1
    position = 100, -150
    halign = center
    valign = center
    # color = rgba(0, 0, 0, 0.5)
    color = $surface
}

#############
### INPUT BOX
#############

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0.5)

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = $primary
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL
    dots_spacing = 0.3
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

#############
### DATE-TIME
#############

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = $primary
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font
    color = $primary
    position = 0, 100
    halign = center
    valign = center
}

#############
### Suspend Button
#############

label {
    monitor =
    text = 󰤄 
    color = $primary
    onclick = systemctl suspend
    halign = center
    valign = center
    position = 3,-150
    font_size = $emoji_font_size
    font_family = $emoji_font
}

#############
### Shutdown Button
#############

label {
    monitor =
    text = 󰐥 
    color = $primary
    onclick = shutdown now
    halign = center
    valign = center
    position = -97,-150
    font_size = $emoji_font_size
    font_family = $emoji_font
}

#############
### Reboot Button
#############

label {
    monitor =
    text = 󰜉 
    color = $primary
    onclick = reboot
    halign = center
    valign = center
    position = 103,-150
    font_size = $emoji_font_size
    font_family = $emoji_font
}
