#############################################################
###                       HYPRSHOT                        ###
#############################################################

##############################
### KEYBINDS
##############################
bind = $mod SHIFT, S, exec, hyprshot -zm region
bind = $mod, S, exec, hyprshot -zm region --clipboard-only
