#############################################################
###                       HYPRSHOT                        ###
#############################################################

##############################
### KEYBINDS
##############################
bind = $mod SHIFT, S, exec, hyprshot -zm region --output-folder ~/Pictures/hyprshot/
bind = $mod, S, exec, hyprshot -zm region --output-folder ~/Pictures/hyprshot/
