source = ~/.config/.colors/hyprland-colors.conf

#####################
### GENERAL WINDOW
#####################

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    resize_on_border = false
    allow_tearing = false
}

decoration {
    rounding = 10
    rounding_power = 1

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = $shadow
    }

    blur {
        enabled = true
        size = 3
        passes = 4

        vibrancy = 0.1696
    }
}

#####################
### ACTIVE WINDOW
#####################

general {
    col.active_border = rgba(fbb767a0)
}

decoration {
    active_opacity = 0.9
}

#####################
### INACTIVE WINDOW
#####################

general {
    col.inactive_border = rgba(c89de480)
}

decoration {
    inactive_opacity = 0.95
}

#####################
### WALLPAPERS
#####################

misc {
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

#####################
### ANIMATIONS
#####################

animations {
    enabled = true

    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1
    bezier = overshoot,      0.05, 0.9,  0.1,  1.1

#####################
### General
#####################

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  overshoot
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = zoomFactor,    1,     7,     quick

#####################
### WINDOWS
#####################

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%

#####################
### WORKSPACES
#####################

    # animation = workspaces,          1,     1.94,  almostLinear, fade
    #           NAME,                ONOFF, SPEED, CURVE,        [STYLE]1
    animation = workspacesIn,        1,     1.21,  almostLinear, slidefadevert -100%
    animation = workspacesOut,       1,     1.94,  almostLinear, slidefade     100%

    animation = specialWorkspace,    1,     1.94,  almostLinear, slidefadevert 30%
    animation = specialWorkspaceIn,  1,     1.21,  almostLinear, slidefadevert 30%
    animation = specialWorkspaceOut, 1,     1.94,  almostLinear, slidefadevert 30%
}
