#############################################################
###                     INPUT DEVICES                     ###
#############################################################

######################
### GENERAL
######################

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.8 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

######################
### MOUSE
######################

device {
    name = razer-razer-basilisk-v2-keyboard-1
    sensitivity = 1.0
    scroll_factor=1
}

######################
### KEYBOARD
######################

device {
    name=razer-razer-blackwidow-chroma-v2
}

######################
### TOUCHPAD
######################

gesture = 3, horizontal, workspace

#############################################################
###                    OUTPUT DEVICES                     ###
#############################################################

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, 1920x1200@59.95Hz, 0x0, 1
