#############################################################
###                        LAYOUTS                        ###
#############################################################

general {
    layout = scrolling
}

bind = $mod SHIFT, left,  swapwindow, l
bind = $mod SHIFT, right, swapwindow, r
bind = $mod SHIFT, up,    swapwindow, u
bind = $mod SHIFT, down,  swapwindow, d

bind = $mod,       left,  movefocus, l
bind = $mod,       right, movefocus, r
bind = $mod,       up,    movefocus, u
bind = $mod,       down,  movefocus, d

##############################
### MASTER LAYOUT CONFIG
##############################
master {
    new_status = slave
}

##############################
### DWINDLE LAYOUT CONFIG
##############################
dwindle {
    pseudotile = true
    preserve_split = true
    force_split = 2
}

# bind = $mod, P, pseudo
# bind = $mod, O, togglesplit

##############################
### SCROLLING LAYOUT CONFIG
##############################
scrolling {
    column_width = 1.0
    follow_focus = true
    focus_fit_method = 0
    follow_min_visible = 1.0
    explicit_column_widths = 0.5, 1.0
}

bind = $mod, P, layoutmsg, promote
bind = $mod, minus, layoutmsg, colresize -conf
bind = $mod, equal, layoutmsg, colresize +conf

##############################
### MONOCLE LAYOUT CONFIG
##############################
monocle {

}

##############################
### FLOATING LAYOUT CONFIG
##############################
# properties
windowrule = persistent_size 1, match:float 1
# keybinds
bind  = $mod, F,         togglefloating,
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
