#############################################################
###                   WINDOW MANAGEMENT                   ###
#############################################################

##############################
### VARIABLES
##############################
$workspace_key_1 = KP_End
$workspace_key_2 = KP_Down
$workspace_key_3 = KP_Next
$workspace_key_4 = KP_Left
$workspace_key_5 = KP_Begin
$workspace_key_6 = KP_Right
$workspace_key_7 = KP_Home
$workspace_key_8 = KP_Up
$workspace_key_9 = KP_Prior
$workspace_key_0 = KP_Insert

##############################
### PROPERTIES
##############################
workspace = 3, layout:master
workspace = 6, layout:master

##############################
### DEFAULT PROPERTIES
##############################
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*
# Fix some dragging issues with XWayland
windowrule = no_focus 1, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

##############################
### WORKSPACE KEYBINDS
##############################
bind = $mod, $workspace_key_1, workspace, 1
bind = $mod, $workspace_key_2, workspace, 2
bind = $mod, $workspace_key_3, workspace, 3
bind = $mod, $workspace_key_4, workspace, 4
bind = $mod, $workspace_key_5, workspace, 5
bind = $mod, $workspace_key_6, workspace, 6
bind = $mod, $workspace_key_7, workspace, 7
bind = $mod, $workspace_key_8, workspace, 8
bind = $mod, $workspace_key_9, workspace, 9
bind = $mod, $workspace_key_0, workspace, 10

bind = $mod CTRL, right, workspace, r+1
bind = $mod CTRL, left,  workspace, r-1
bind = $mod CTRL, up,    workspace, r+3
bind = $mod CTRL, down,  workspace, r-3

##############################
### WINDOW KEYBINDS
##############################
bind = $mod SHIFT, $workspace_key_1, movetoworkspacesilent, 1
bind = $mod SHIFT, $workspace_key_2, movetoworkspacesilent, 2
bind = $mod SHIFT, $workspace_key_3, movetoworkspacesilent, 3
bind = $mod SHIFT, $workspace_key_4, movetoworkspacesilent, 4
bind = $mod SHIFT, $workspace_key_5, movetoworkspacesilent, 5
bind = $mod SHIFT, $workspace_key_6, movetoworkspacesilent, 6
bind = $mod SHIFT, $workspace_key_7, movetoworkspacesilent, 7
bind = $mod SHIFT, $workspace_key_8, movetoworkspacesilent, 8
bind = $mod SHIFT, $workspace_key_9, movetoworkspacesilent, 9
bind = $mod SHIFT, $workspace_key_0, movetoworkspacesilent, 10

bind = $mod CTRL SHIFT, right, movetoworkspacesilent, r+1
bind = $mod CTRL SHIFT, left,  movetoworkspacesilent, r-1
bind = $mod CTRL SHIFT, up,    movetoworkspacesilent, r+3
bind = $mod CTRL SHIFT, down,  movetoworkspacesilent, r-3

bind = $mod, KP_Subtract, killactive
bind = $mod, delete, killactive
bind = $mod, W, fullscreen
