#############################################################
###                       HYPRPAPER                       ###
#############################################################

##############################
### AUTOSTART
##############################
exec-once = systemctl --user start hyprpaper
