######################
### ENVIRONMENT
######################

$mod = SUPER_L

source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/devices.conf
source = ~/.config/hypr/config/aesthetics.conf

######################
### WINDOWS & WORKSPACES
######################

source = ~/.config/hypr/config/layouts.conf
source = ~/.config/hypr/config/windows.conf
source = ~/.config/hypr/config/workspaces.conf

######################
### APPS & UTILS
######################
source = ~/.config/hypr/system/*.conf
source = ~/.config/hypr/apps/*.conf
