#############################################################
###                       SWAYLOCK                        ###
#############################################################

##############################
### VARIABLES
##############################
$screenlock_name=swaylock
$screenlock_cmd=swaylock -f -C ~/.config/swaylock/config

##############################
### KEYBINDS
##############################
bind = $mod, L, exec, $screenlock_cmd
